// Code generated by go-swagger; DO NOT EDIT.

package inventory

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GenerateClusterISOReader is a Reader for the GenerateClusterISO structure.
type GenerateClusterISOReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GenerateClusterISOReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewGenerateClusterISONoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGenerateClusterISOBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGenerateClusterISONotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewGenerateClusterISOConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGenerateClusterISOInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGenerateClusterISONoContent creates a GenerateClusterISONoContent with default headers values
func NewGenerateClusterISONoContent() *GenerateClusterISONoContent {
	return &GenerateClusterISONoContent{}
}

/*GenerateClusterISONoContent handles this case with default header values.

Success.
*/
type GenerateClusterISONoContent struct {
}

func (o *GenerateClusterISONoContent) Error() string {
	return fmt.Sprintf("[POST /clusters/{clusterId}/downloads/image][%d] generateClusterISONoContent ", 204)
}

func (o *GenerateClusterISONoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGenerateClusterISOBadRequest creates a GenerateClusterISOBadRequest with default headers values
func NewGenerateClusterISOBadRequest() *GenerateClusterISOBadRequest {
	return &GenerateClusterISOBadRequest{}
}

/*GenerateClusterISOBadRequest handles this case with default header values.

Invalid input
*/
type GenerateClusterISOBadRequest struct {
}

func (o *GenerateClusterISOBadRequest) Error() string {
	return fmt.Sprintf("[POST /clusters/{clusterId}/downloads/image][%d] generateClusterISOBadRequest ", 400)
}

func (o *GenerateClusterISOBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGenerateClusterISONotFound creates a GenerateClusterISONotFound with default headers values
func NewGenerateClusterISONotFound() *GenerateClusterISONotFound {
	return &GenerateClusterISONotFound{}
}

/*GenerateClusterISONotFound handles this case with default header values.

Cluster not found
*/
type GenerateClusterISONotFound struct {
}

func (o *GenerateClusterISONotFound) Error() string {
	return fmt.Sprintf("[POST /clusters/{clusterId}/downloads/image][%d] generateClusterISONotFound ", 404)
}

func (o *GenerateClusterISONotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGenerateClusterISOConflict creates a GenerateClusterISOConflict with default headers values
func NewGenerateClusterISOConflict() *GenerateClusterISOConflict {
	return &GenerateClusterISOConflict{}
}

/*GenerateClusterISOConflict handles this case with default header values.

Conflict
*/
type GenerateClusterISOConflict struct {
}

func (o *GenerateClusterISOConflict) Error() string {
	return fmt.Sprintf("[POST /clusters/{clusterId}/downloads/image][%d] generateClusterISOConflict ", 409)
}

func (o *GenerateClusterISOConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGenerateClusterISOInternalServerError creates a GenerateClusterISOInternalServerError with default headers values
func NewGenerateClusterISOInternalServerError() *GenerateClusterISOInternalServerError {
	return &GenerateClusterISOInternalServerError{}
}

/*GenerateClusterISOInternalServerError handles this case with default header values.

Internal server error
*/
type GenerateClusterISOInternalServerError struct {
}

func (o *GenerateClusterISOInternalServerError) Error() string {
	return fmt.Sprintf("[POST /clusters/{clusterId}/downloads/image][%d] generateClusterISOInternalServerError ", 500)
}

func (o *GenerateClusterISOInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
