// Code generated by go-swagger; DO NOT EDIT.

package inventory

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GenerateClusterISONoContentCode is the HTTP code returned for type GenerateClusterISONoContent
const GenerateClusterISONoContentCode int = 204

/*GenerateClusterISONoContent Success.

swagger:response generateClusterISONoContent
*/
type GenerateClusterISONoContent struct {
}

// NewGenerateClusterISONoContent creates GenerateClusterISONoContent with default headers values
func NewGenerateClusterISONoContent() *GenerateClusterISONoContent {

	return &GenerateClusterISONoContent{}
}

// WriteResponse to the client
func (o *GenerateClusterISONoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// GenerateClusterISOBadRequestCode is the HTTP code returned for type GenerateClusterISOBadRequest
const GenerateClusterISOBadRequestCode int = 400

/*GenerateClusterISOBadRequest Invalid input

swagger:response generateClusterISOBadRequest
*/
type GenerateClusterISOBadRequest struct {
}

// NewGenerateClusterISOBadRequest creates GenerateClusterISOBadRequest with default headers values
func NewGenerateClusterISOBadRequest() *GenerateClusterISOBadRequest {

	return &GenerateClusterISOBadRequest{}
}

// WriteResponse to the client
func (o *GenerateClusterISOBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// GenerateClusterISONotFoundCode is the HTTP code returned for type GenerateClusterISONotFound
const GenerateClusterISONotFoundCode int = 404

/*GenerateClusterISONotFound Cluster not found

swagger:response generateClusterISONotFound
*/
type GenerateClusterISONotFound struct {
}

// NewGenerateClusterISONotFound creates GenerateClusterISONotFound with default headers values
func NewGenerateClusterISONotFound() *GenerateClusterISONotFound {

	return &GenerateClusterISONotFound{}
}

// WriteResponse to the client
func (o *GenerateClusterISONotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// GenerateClusterISOConflictCode is the HTTP code returned for type GenerateClusterISOConflict
const GenerateClusterISOConflictCode int = 409

/*GenerateClusterISOConflict Conflict

swagger:response generateClusterISOConflict
*/
type GenerateClusterISOConflict struct {
}

// NewGenerateClusterISOConflict creates GenerateClusterISOConflict with default headers values
func NewGenerateClusterISOConflict() *GenerateClusterISOConflict {

	return &GenerateClusterISOConflict{}
}

// WriteResponse to the client
func (o *GenerateClusterISOConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(409)
}

// GenerateClusterISOInternalServerErrorCode is the HTTP code returned for type GenerateClusterISOInternalServerError
const GenerateClusterISOInternalServerErrorCode int = 500

/*GenerateClusterISOInternalServerError Internal server error

swagger:response generateClusterISOInternalServerError
*/
type GenerateClusterISOInternalServerError struct {
}

// NewGenerateClusterISOInternalServerError creates GenerateClusterISOInternalServerError with default headers values
func NewGenerateClusterISOInternalServerError() *GenerateClusterISOInternalServerError {

	return &GenerateClusterISOInternalServerError{}
}

// WriteResponse to the client
func (o *GenerateClusterISOInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
